name = "oslofjorden"
data_root = "~/FjordSim_data"

[grid]
size = [232, 105, 18]
halo = [7, 7, 7]
longitude = [10.2, 11.02]
latitude = [59.0, 59.93]
z_faces = [
    -450.0,
    -400.0,
    -350.0,
    -300.0,
    -250.0,
    -200.0,
    -150.0,
    -100.0,
    -75.0,
    -50.0,
    -25.0,
    -15.0,
    -10.0,
    -7.5,
    -5.0,
    -3.0,
    -2.0,
    -1.0,
    0.0,
]

[bathymetry]
geodatabase_path = "Basisdata_0000_Norge_25833_Dybdedata_FGDB.gdb"
raw_resolution_factor = 3
padding_cells = 0
include_contours = false
contour_stride = 1
interpolation_passes = 3
major_basins = 1
geonorge_cache = false
regrid_cache = false

[forcing.norkyst]
catalog_url = "https://thredds.met.no/thredds/catalog/fou-hi/norkyst800m/catalog.xml"
opendap_url = "https://thredds.met.no/thredds/dodsC/fou-hi/norkyst800m/"
parameters = ["temperature", "salinity", "u_eastward", "v_northward"]
years = [2020]
